local utils = require("thesis.utils")
utils.cfg("nvim-treesitter")
utils.cfg("kanagawa")
utils.cfg("neorg")
utils.cfg("leap")
utils.cfg("telescope")
utils.cfg("vimtex")
utils.cfg("surround")
utils.cfg("marks")
utils.cfg("heirline")
utils.cfg("satellite")
