local utils = require("thesis.utils")
utils.cfg("colors", "nvim-treesitter")
utils.cfg("colors", "kanagawa")
utils.cfg("markup", "neorg")
utils.cfg("navigation", "leap")
utils.cfg("navigation", "telescope")
utils.cfg("markup", "vimtex")
utils.cfg("navigation", "surround")
utils.cfg("navigation", "marks")
utils.cfg("ui", "heirline")
utils.cfg("ui", "satellite")
