vim.api.nvim_create_augroup("Manager", {})
require("thesis.modules.colors")
require("thesis.modules.completion")
require("thesis.modules.mappings")
require("thesis.modules.markup")
require("thesis.modules.misc")
require("thesis.modules.navigation")
require("thesis.modules.ui")
