local utils = require("thesis.utils")
utils.enable("plenary")
utils.cfg("completion", "luasnip")
utils.cfg("completion", "cmp")
utils.enable("cmp_luasnip")
utils.enable("cmp_nvim_lsp")
utils.enable("cmp_buffer")
utils.enable("cmp_path")
utils.cfg("ui", "sidebar-nvim")
utils.cfg("mappings", "mappy")
