local utils = require("thesis.utils")
utils.enable("plenary")
utils.cfg("luasnip")
utils.cfg("cmp")
utils.enable("cmp_luasnip")
utils.enable("cmp_nvim_lsp")
utils.enable("cmp_buffer")
utils.enable("cmp_path")
utils.cfg("sidebar-nvim")
utils.cfg("mappy")
